# -*- coding: utf-8 -*-
"""13.one-hot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p2Z_p6kGpUN9e_BVRZm5OrZg5Tlk0rP3

# One-Hot Encoding 獨熱碼
- one-hot encoding是用來向量表示字詞的方式，特點是每一個字詞之間皆為正交(orthogonal)
- 字詞向量正交，才能排除字詞之間互相影響
- one-hot的優點也是缺點，不同詞的向量正交，無法衡量不同詞之間的關係
- 只能反映某個詞是否在句中出現，無法衡量詞的重要性
- one-hot是高維稀疏矩陣，浪費計算能力與儲存空間
- 本範例示範如何把國家表示成one-hot encoding表示法
"""

import numpy as np
import pandas as pd
country=['Taiwan','Australia','Ireland','Australia','Ireland','Taiwan']
age=[25,30,45,35,22,36]
salary=[20000,32000,59000,60000,43000,52000]
dic={'Country':country,'Age':age,'Salary':salary}
data=pd.DataFrame(dic)
data

"""## Label encoding
利用LabelEcoder函數，將Country欄位進行Label encoding編碼<br>
Australia：0<br>
Ireland：1<br>
Taiwan：2<br>
"""

from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
data_le=pd.DataFrame(dic)
data_le['Country'] = labelencoder.fit_transform(data['Country'])
data_le

"""## One hot encoding
利用OneHotEcoder函數，將Country欄位進行Ont-Hot encoding編碼
<table><tr><td>Australia(0)</td><td>Ireland(1)</td><td>Taiwan(2)</td></tr></table>
"""

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')
data_str_ohe=ct.fit_transform(data_le)
pd.DataFrame(data_str_ohe)

"""## Pandas.get_dummies"""

data_dum = pd.get_dummies(data)
pd.DataFrame(data_dum)